export const RecentArival = [
	{
		id: 1,
		brand: 'Samsung ',
		title: 'Samsung Notebook Flash',
		slug: 'Samsung-Notebook-Flash',
		img: 21,
		imgHover: 16,
		processor: 'Intel Pentium',
		video_card: 'CPU Integrated',
		size: '13.3 inch',
		price: 260,
		storage: '64GB',
		Ram: '4GB ',
		description:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit totam blanditiis laudantium nostrum laboriosam obcaecati magni impedit explicabo optio commodi. Quisquam possimus perferendis optio voluptatem corrupti rem qui fugiat labore.',
	},
	{
		id: 2,
		brand: 'Samsung',
		title: 'Samsung Galaxy Book',
		slug: 'Samsung-Galaxy-Book',
		img: 3,
		imgHover: 18,
		special: true,
		processor: 'Intel i5-10210U',
		video_card: 'Intel HD Graphics 620',
		size: '13.3 inch',
		price: 860,
		storage: '256GB',
		Ram: '8GB ',
		description:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit totam blanditiis laudantium nostrum laboriosam obcaecati magni impedit explicabo optio commodi. Quisquam possimus perferendis optio voluptatem corrupti rem qui fugiat labore.',
	},

	{
		id: 3,
		brand: 'Apple ',
		title: 'Apple MacBook Pro 15 ',
		slug: 'Apple-MacBook-Pro-15',
		img: 2,
		imgHover: 19,
		special: true,
		processor: 'Intel i9-9980HK,',
		video_card: 'AMD Radeon Pro 555X',
		price: 2235,
		size: '15.4 inch',
		storage: '256GB',
		Ram: '16GB ',
		price: '2235',
		description:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit totam blanditiis laudantium nostrum laboriosam obcaecati magni impedit explicabo optio commodi. Quisquam possimus perferendis optio voluptatem corrupti rem qui fugiat labore.',
	},
	{
		id: 4,
		brand: 'Apple ',
		title: 'Apple MacBook Air',
		slug: 'Apple-MacBook-Air',
		img: 7,
		imgHover: 20,
		processor: 'Intel i3-1000NG4',
		video_card: ' Intel Iris Plus Graphics G4',
		price: 435,
		size: '15.4 inch',
		storage: '256GB',
		Ram: '16GB ',
		price: '2235',
		description:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit totam blanditiis laudantium nostrum laboriosam obcaecati magni impedit explicabo optio commodi. Quisquam possimus perferendis optio voluptatem corrupti rem qui fugiat labore.',
	},
	{
		id: 5,
		brand: 'HP ',
		title: 'HP Pavilion',
		slug: 'HP-Pavilion',
		img: 16,
		imgHover: 4,
		processor: 'Intel i5-10300H',
		video_card: 'NVIDIA GeForce GTX 1050',
		price: 635,
		size: '15.6 inch',
		storage: '256GB',
		Ram: '12GB',
		price: '808',
		description:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit totam blanditiis laudantium nostrum laboriosam obcaecati magni impedit explicabo optio commodi. Quisquam possimus perferendis optio voluptatem corrupti rem qui fugiat labore.',
	},
	{
		id: 6,
		brand: 'HP ',
		title: 'HP EliteBook 840',
		slug: 'HP-EliteBook-840',
		img: 5,
		imgHover: 3,
		special: true,
		processor: 'Intel i7-8550U',
		video_card: 'Intel HD Graphics 620',
		price: 1393,
		size: '15.6 inch',
		storage: '256GB',
		Ram: '12GB',
		description:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit totam blanditiis laudantium nostrum laboriosam obcaecati magni impedit explicabo optio commodi. Quisquam possimus perferendis optio voluptatem corrupti rem qui fugiat labore.',
	},
	{
		id: 7,
		brand: 'lenovo',
		title: 'Lenovo Education 14e',
		slug: 'Lenovo-Education-14e',
		img: 13,
		imgHover: 1,
		processor: 'AMD A4-9120C',
		video_card: 'AMD Radeon R4',
		price: 301,
		size: '14 inch',
		storage: '32GB',
		Ram: '4GB',
		description:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit totam blanditiis laudantium nostrum laboriosam obcaecati magni impedit explicabo optio commodi. Quisquam possimus perferendis optio voluptatem corrupti rem qui fugiat labore.',
	},
	{
		id: 8,
		brand: 'lenovo',
		title: 'Lenovo Ideapad D330-10',
		slug: 'Lenovo-Ideapad-D330-14e',
		img: 25,
		imgHover: 9,
		special: true,
		processor: 'Intel Celeron N4000',
		video_card: 'Intel HD Graphics 600',
		price: 272,
		size: '10.1 inch',
		storage: '32GB',
		Ram: '2GB',
		description:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit totam blanditiis laudantium nostrum laboriosam obcaecati magni impedit explicabo optio commodi. Quisquam possimus perferendis optio voluptatem corrupti rem qui fugiat labore.',
	},
	{
		id: 9,
		brand: 'Dell',
		title: 'Dell Inspiron 14 3482',
		slug: 'Dell-Inspiron-14-3482',
		img: 15,
		imgHover: 23,
		processor: 'Intel i3-8145U',
		video_card: 'Intel HD Graphics 620',
		price: 372,
		size: '14 inch',
		storage: ' 1000GB',
		Ram: ' 4GB',
		description:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit totam blanditiis laudantium nostrum laboriosam obcaecati magni impedit explicabo optio commodi. Quisquam possimus perferendis optio voluptatem corrupti rem qui fugiat labore.',
	},
	{
		id: 10,
		brand: 'Dell',
		title: 'Dell Vostro 14 5481',
		slug: 'Dell-Vostro-14-5481',
		img: 17,
		imgHover: 2,
		processor: 'Intel i5-8265U',
		video_card: 'Intel HD Graphics 620',
		price: 572,
		size: '14 inch',
		storage: ' 256GB',
		Ram: '  8GB ',
		description:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit totam blanditiis laudantium nostrum laboriosam obcaecati magni impedit explicabo optio commodi. Quisquam possimus perferendis optio voluptatem corrupti rem qui fugiat labore.',
	},
	{
		id: 11,
		brand: 'Acer',
		title: 'Acer Chromebook 15',
		slug: 'Acer-Chromebook-15',
		img: 20,
		imgHover: 16,
		special: true,
		processor: 'Intel Pentium N4200',
		video_card: 'Intel HD Graphics 505',
		price: 330,
		size: '15.6 inch',
		storage: '32GB',
		Ram: '4GB',
		description:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit totam blanditiis laudantium nostrum laboriosam obcaecati magni impedit explicabo optio commodi. Quisquam possimus perferendis optio voluptatem corrupti rem qui fugiat labore.',
	},
	{
		id: 12,
		brand: 'Acer',
		title: 'Acer Aspire Nitro 7',
		slug: 'Acer-Aspire-Nitro-7',
		img: 6,
		imgHover: 11,
		processor: 'NVIDIA GeForce GTX 1050',
		video_card: 'Intel HD Graphics 505',
		price: 1056,
		size: '15.6 inch',
		storage: '256GB',
		Ram: '8GB ',
		description:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit totam blanditiis laudantium nostrum laboriosam obcaecati magni impedit explicabo optio commodi. Quisquam possimus perferendis optio voluptatem corrupti rem qui fugiat labore.',
	},
];

export const SubbannerRight = [
	{
		pretitle: 'exchange offer',
		title: 'Lenovo Ideapad D330-10',
		img: 25,
	},
	{
		pretitle: 'Mega Deal',
		title: 'HP EliteBook 1040 G3',
		img: 5,
	},
	{
		pretitle: 'Big Sale',
		title: 'Samsung Galaxy Book flex 13',
		img: 3,
	},
];

export const SubbannerLeft = [
	{
		pretitle: 'exchange offer',
		title: 'Samsung Notebook Flash',
		img: 21,
	},
	{
		pretitle: 'Mega Deal',
		title: 'Apple MacBook Pro 15 (2019)',
		img: 2,
	},
	{
		pretitle: 'Big Sale',
		title: 'Acer Aspire Nitro  VN7-792G',
		img: 11,
	},
];
